on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: window

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # change to match your project

      - name: Build with Maven
        run: mvn clean package -DskipTests  # or use Gradle if needed

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-app
     
          path: target/*.jar  # adjust path if different

      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # # - name: Deploy to Azure Spring Apps
      #   uses: azure/spring-apps-deploy@v1
      #   with:
      #     app-name: YOUR_APP_NAME
      #     service-name: YOUR_SPRING_APP_SERVICE
      #     resource-group: YOUR_RESOURCE_GROUP
      #     package: target/*.jar  # or build/libs/*.jar for Gradle
